#!/usr/bin/env bash
# ============================================================================
# SiteForge 数据备份脚本
#
# 功能：
#   - 备份 PostgreSQL 数据库（自定义格式，支持选择性恢复）
#   - 备份媒体文件目录
#   - 按 BACKUP_RETENTION_DAYS 自动清理过期备份
#
# 用法：
#   bash scripts/backup.sh                  # 立即执行一次备份
#   bash scripts/backup.sh --cron           # cron 模式（输出更简洁）
#
# 推荐 cron 配置（每日凌晨 3 点备份）：
#   0 3 * * * cd /opt/siteforge && bash scripts/backup.sh --cron >> /var/log/siteforge-backup.log 2>&1
# ============================================================================

set -euo pipefail

# ----- 加载环境变量 -----
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

if [[ -f .env ]]; then
    set -a
    # shellcheck disable=SC1091
    source .env
    set +a
fi

# ----- 配置 -----
BACKUP_DIR="${BACKUP_DIR:-./data/backups}"
RETENTION_DAYS="${BACKUP_RETENTION_DAYS:-7}"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
BACKUP_SUBDIR="${BACKUP_DIR}/${TIMESTAMP}"

POSTGRES_DB="${POSTGRES_DB:-siteforge}"
POSTGRES_USER="${POSTGRES_USER:-siteforge}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-}"
POSTGRES_CONTAINER="${POSTGRES_CONTAINER:-siteforge-postgres}"

MEDIA_DIR="${MEDIA_DIR:-./data/media}"
SITES_DIR="${SITES_DIR:-./data/sites}"

CRON_MODE=false
[[ "${1:-}" == "--cron" ]] && CRON_MODE=true

log() {
    if $CRON_MODE; then
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
    else
        echo ">>> $*"
    fi
}

error_exit() {
    echo "!!! 错误：$*" >&2
    exit 1
}

# ----- 开始备份 -----
log "开始 SiteForge 数据备份"
log "备份目录：${BACKUP_SUBDIR}"

mkdir -p "$BACKUP_SUBDIR" || error_exit "无法创建备份目录"

# ----- 1. 备份 PostgreSQL 数据库 -----
log "备份数据库 ${POSTGRES_DB}..."

if docker ps --format '{{.Names}}' | grep -q "^${POSTGRES_CONTAINER}$"; then
    # 通过 docker exec 调用 pg_dump
    PGPASSWORD="$POSTGRES_PASSWORD" docker exec -e PGPASSWORD="$POSTGRES_PASSWORD" \
        "$POSTGRES_CONTAINER" \
        pg_dump -U "$POSTGRES_USER" -d "$POSTGRES_DB" -F c -f /tmp/siteforge.dump \
        || error_exit "pg_dump 失败"

    docker cp "${POSTGRES_CONTAINER}:/tmp/siteforge.dump" "${BACKUP_SUBDIR}/postgres.dump" \
        || error_exit "拷贝备份文件失败"

    docker exec "$POSTGRES_CONTAINER" rm -f /tmp/siteforge.dump
    log "数据库备份完成：${BACKUP_SUBDIR}/postgres.dump ($(du -h "${BACKUP_SUBDIR}/postgres.dump" | cut -f1))"
else
    # 直接调用本地 pg_dump（开发环境）
    if command -v pg_dump >/dev/null 2>&1; then
        PGPASSWORD="$POSTGRES_PASSWORD" pg_dump -h localhost -U "$POSTGRES_USER" "$POSTGRES_DB" -F c \
            -f "${BACKUP_SUBDIR}/postgres.dump" || error_exit "pg_dump 失败"
        log "数据库备份完成（本地 pg_dump）"
    else
        log "警告：未找到 PostgreSQL 容器或 pg_dump 命令，跳过数据库备份"
    fi
fi

# ----- 2. 备份媒体文件 -----
if [[ -d "$MEDIA_DIR" ]]; then
    log "备份媒体文件..."
    tar -czf "${BACKUP_SUBDIR}/media.tar.gz" -C "$(dirname "$MEDIA_DIR")" "$(basename "$MEDIA_DIR")" \
        || error_exit "媒体文件打包失败"
    log "媒体备份完成：$(du -h "${BACKUP_SUBDIR}/media.tar.gz" | cut -f1)"
else
    log "媒体目录不存在，跳过：$MEDIA_DIR"
fi

# ----- 3. 备份静态站点产物（可选，体积较大，默认跳过） -----
if [[ "${BACKUP_SITES:-false}" == "true" && -d "$SITES_DIR" ]]; then
    log "备份静态站点产物..."
    tar -czf "${BACKUP_SUBDIR}/sites.tar.gz" -C "$(dirname "$SITES_DIR")" "$(basename "$SITES_DIR")" \
        || error_exit "站点产物打包失败"
    log "站点产物备份完成：$(du -h "${BACKUP_SUBDIR}/sites.tar.gz" | cut -f1)"
fi

# ----- 4. 备份 .env 配置（脱敏：移除密码字段后保留） -----
if [[ -f .env ]]; then
    cp .env "${BACKUP_SUBDIR}/.env.backup"
    log ".env 配置已备份"
fi

# ----- 5. 写入备份元信息 -----
cat > "${BACKUP_SUBDIR}/MANIFEST.txt" <<EOF
SiteForge Backup Manifest
=========================
Timestamp:        ${TIMESTAMP}
Backup directory: ${BACKUP_SUBDIR}
Generated by:     $(whoami)@$(hostname)
Files:
$(ls -la "${BACKUP_SUBDIR}" | tail -n +2)
EOF

# ----- 6. 清理过期备份 -----
log "清理超过 ${RETENTION_DAYS} 天的旧备份..."
deleted=0
while IFS= read -r dir; do
    if [[ -d "$dir" ]]; then
        rm -rf "$dir"
        log "已删除过期备份：$(basename "$dir")"
        deleted=$((deleted + 1))
    fi
done < <(find "$BACKUP_DIR" -maxdepth 1 -type d -mtime "+${RETENTION_DAYS}" ! -path "$BACKUP_DIR")

log "清理完成，删除了 ${deleted} 个过期备份"

# ----- 7. 输出最新备份路径（便于恢复脚本引用） -----
ln -sfn "${BACKUP_SUBDIR}" "${BACKUP_DIR}/latest" 2>/dev/null || true

log "备份成功：${BACKUP_SUBDIR}"
log "  恢复命令：bash scripts/restore.sh ${BACKUP_SUBDIR}"
